indent_width = 2
indent_type = "Spaces"
quote_style = "AutoPreferDouble"
line_endings = "Unix"
column_width = 120
call_parentheses = "Input"
collapse_simple_statement = "FunctionOnly"

[sort_requires]
enabled = false
